# for local development
version: "3.7"
services:
  quasar:
    build:
      context: .
      target: "develop-stage"
      dockerfile: ./docker/test/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    command: /bin/sh -c "yarn && quasar dev"
